dataSources:
  ds_master:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:33309/test1202?characterEncoding=utf-8
    username: root
    password: root
  ds_slave0:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:33306/test1202?characterEncoding=utf-8
    username: root
    password: root

masterSlaveRule:
  name: ds_ms
  masterDataSourceName: ds_master
  slaveDataSourceNames: [ds_slave0]

props:
  sql.show: true
